### ISSUE TITLE
Considerations for Visual Impairment

### ISSUE THREAD

**Issue by SimonAytes** [yu-takagi/StableDiffusionReconstruction#3]
In the initial dataset, were the factors of visual impairment (e.g. color blindness or glasses) tracked for the participants?

If so, do you think this would have an effect on the fMRI reconstruction of the images?

**Comment by yu-takagi** [comment]
@SimonAytes Thanks for your question! This information is written in the [original dataset paper](https://www.nature.com/articles/s41593-021-00962-x#Sec14):

> The NSD study was advertised to the University of Minnesota community. We sought to recruit right-handed individuals (18–65 years old) with no known cognitive deficits or color blindness and with normal or corrected-to-normal vision.
